name: Playwright CI

env:
  echo "USERNAMETOLOGIN: $USERNAMETOLOGIN"
  echo "PASSWORD: $PASSWORD"
  USERNAMETOLOGIN: ${{ secrets.USERNAMETOLOGIN }}
  PASSWORD: ${{ secrets.PASSWORD }}
on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Select Runner"
        required: true
        type: choice
        options:
          - github-hosted
          - self-hosted

jobs:
  test:
    runs-on: ${{ github.event.inputs.runner == 'self-hosted' && 'self-hosted' || 'windows-latest' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Inject Environment Variables
        run: |
          echo "USERNAME=${{ secrets.APP_USERNAME }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.APP_PASSWORD }}" >> $GITHUB_ENV

      - name: Run Tests (Headed)
        run: npm run sanity -- --headed

      # Upload HTML Report
      - name: Upload Playwright Report (HTML)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/

      # âœ… Upload screenshots, traces & videos on failure
      - name: Upload Test Results (Screenshots, Traces, Videos)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-debug-artifacts
          path: |
            test-results/
            **/trace.zip
            **/*.png
            **/*.mp4
          retention-days: 7
